version: 2
builds:
  - binary: helmizer
    dir: ./src
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{ .Version }}
    goarch:
      - amd64
      - arm64
      - '386'
    goos:
      - linux
      - darwin
      - windows
    ignore:
      - goos: darwin
        goarch: '386'
    id: helmizer
checksum:
  name_template: checksums.txt
release:
  draft: true
  use_existing_draft: true
  replace_existing_artifacts: true
changelog:
  use: github-native
