releases:
  - chart: jetstack/cert-manager
    name: cert-manager
    namespace: cert-manager
    values:
      - global:
          commonLabels:
            dude: helmizer
    version: 1.14.3
repositories:
  - name: jetstack
    url: https://charts.jetstack.io
helmDefaults:
  skipDeps: true  # https://github.com/helmfile/helmfile/issues/50
