helmizer:
  commandSequence:
  - command: "helm"
    args:
      - "-n"
      - "default"
      - "template"
      - "ingress-nginx"
      - --output-dir
      - '.'
      - --include-crds
      - --skip-tests
      - --version
      - '4.0.6'
      - ingress-nginx/ingress-nginx
  dry-run: false
  kustomization-directory: .
  kustomization-file-name: kustomization.yaml
  sort-keys: true
  version: '0.1.0'
kustomize:
  namespace: default
  resources:
    - ingress-nginx/admission-webhooks/
    - ingress-nginx/templates/
  configMapGenerator:
    - name: test-env
      namespace: default
      envs:
        - .env
    - name: test-env-duplicate
      namespace: default
      envs:
        - .env
