helmizer:
  preCommands:
    - command: "helmfile"
      args:
        - template
        - --skip-deps
        - --output-dir-template
        - "../"
kustomize:
  namespace: default
  resources:
    - cert-manager/
  configMapGenerator:
    - name: test-env
      namespace: default
      envs:
        - .env
    - name: test-env-duplicate
      namespace: default
      envs:
        - .env
