apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
replacements:
  - source:
      fieldPath: metadata.name
      kind: Deployment
    targets:
      - select:
          name: some-resource
