apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesJson6902:
  - path: add_init_container.yaml
    target:
      kind: Deployment
      name: my-deployment
      version: v1
  - path: add_service_annotation.yaml
    target:
      kind: Service
      name: my-service
      version: v1
